version: "3.9"
services:
  server:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
  web: 
    build: ./client
    ports:
      - "5173:3000"
    depends_on:
      - server